# Generated by Django 3.1.1 on 2020-11-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('Edificio', models.CharField(max_length=30)),
                ('capacidad', models.PositiveIntegerField()),
            ],
        ),
    ]
