# Generated by Django 3.1.1 on 2020-11-13 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_salones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salones',
            old_name='Edificio',
            new_name='edificio',
        ),
    ]
