# Generated by Django 3.1.1 on 2021-01-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210114_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='salon',
        ),
    ]
