# Generated by Django 3.1.1 on 2021-01-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210127_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='salonAsignado',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='api.salones'),
            preserve_default=False,
        ),
    ]
