# Generated by Django 3.1.1 on 2021-01-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_persona_salonasignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='salonAsignado',
        ),
    ]
